FutureForex/FutureForex/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", RedirectView.as_view(url="/documents/")),
    path("documents/", include("documents.urls")),
]

FutureForex/documents/urls.py
from django.urls import path

from .views import (
    CustomerListView,
    DocumentView,
    NotificationView,
    upload_file,
    create_document_request,
    mark_notification_read,
    get_unread_notification_count,
    mark_all_notifications_read,
    download_document,
)
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path("", RedirectView.as_view(url="/documents/customers/")),
    path("customers/", CustomerListView.as_view(), name="customer_list"),
    path("documents/", DocumentView.as_view(), name="document_list"),
    path("documents/create", create_document_request, name="create_document_request"),
    path(
        "documents/download/<str:upload_id>",
        download_document,
        name="download_document",
    ),
    path("notifications/", NotificationView.as_view(), name="notification_list"),
    path(
        "notifications/read/<str:notification_id>/",
        mark_notification_read,
        name="mark_notification_read",
    ),
    path(
        "notifications/read/all>",
        mark_all_notifications_read,
        name="mark_all_notifications_read",
    ),
    path(
        "notifications/unread/",
        get_unread_notification_count,
        name="get_unread_notification_count",
    ),
    path("upload/<str:upload_id>", upload_file, name="upload_file"),
]

# Serve File uploads locally
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FutureForex/documents/models.py
from django.db import models
from .constants import CHAR_MAX_LENGTH


class UploadStatus(models.IntegerChoices):
    PENDING = (1, "Pending")
    COMPLETED = (2, "Completed")


class FileType(models.IntegerChoices):
    ID = (1, "Identity Document")
    ADDRESS = (2, "Proof of Address")
    OTHER = (3, "Other")


class NotificationType(models.IntegerChoices):
    FILE_UPLOAD = (1, "FileUpload")


class NotificationStatus(models.IntegerChoices):
    UNREAD = (1, "Unread")
    READ = (2, "Read")


class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        abstract = True


class RelationshipManager(BaseModel):
    name = models.CharField(max_length=CHAR_MAX_LENGTH)


class Customer(BaseModel):
    name = models.CharField(max_length=CHAR_MAX_LENGTH)
    email = models.EmailField(unique=True)
    relationship_manager = models.ForeignKey(
        RelationshipManager, on_delete=models.SET_NULL, null=True
    )


class File(BaseModel):
    name = models.CharField(max_length=CHAR_MAX_LENGTH)
    url = models.FileField(upload_to="uploads/")


class Document(BaseModel):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=CHAR_MAX_LENGTH)
    email_blurb = models.TextField()
    file_type = models.IntegerField(choices=FileType.choices)
    status = models.IntegerField(
        choices=UploadStatus.choices, default=UploadStatus.PENDING
    )
    file = models.ForeignKey(File, on_delete=models.SET_NULL, blank=True, null=True)
    upload_id = models.TextField(unique=True)


class Notification(BaseModel):
    relationship_manager = models.ForeignKey(
        RelationshipManager, on_delete=models.CASCADE
    )
    type = models.IntegerField(choices=NotificationType.choices)
    text = models.TextField()
    status = models.IntegerField(
        choices=NotificationStatus.choices, default=NotificationStatus.UNREAD
    )


class EmailTemplate(BaseModel):
    # For now make unique but can eventually have multiple templates per type that RM can select from
    file_type = models.IntegerField(choices=FileType.choices, unique=True)
    subject = models.TextField()
    body = models.TextField()

FutureForex/documents/forms.py
from django import forms
from .models import (
    File,
    UploadStatus,
    NotificationStatus,
    NotificationType,
    FileType,
)

# Sorting Choices for Ascending and Descending
SORT_CHOICES = [("asc", "Ascending"), ("desc", "Descending")]


# Helper to add the All filter without affecting the original choices
def with_all_choice(choices):
    return [("", "All")] + list(choices)


class FileUploadForm(forms.ModelForm):
    class Meta:
        model = File
        fields = ["url"]


class DocumentRequestForm(forms.Form):
    email = forms.EmailField()
    name = forms.CharField()
    file_type = forms.ChoiceField(choices=FileType.choices)


class DocumentFilterForm(forms.Form):
    email = forms.CharField(required=False)
    status = forms.ChoiceField(
        choices=with_all_choice(UploadStatus.choices), required=False, initial="All"
    )
    sort = forms.ChoiceField(choices=SORT_CHOICES, required=False, initial="desc")


class NotificationFilterForm(forms.Form):
    status = forms.ChoiceField(
        choices=with_all_choice(NotificationStatus.choices),
        required=False,
        initial="All",
    )
    type = forms.ChoiceField(
        choices=with_all_choice(NotificationType.choices), required=False, initial="All"
    )
    sort = forms.ChoiceField(choices=SORT_CHOICES, required=False, initial="desc")


class CustomerFilterForm(forms.Form):
    email = forms.CharField(required=False)
    name = forms.CharField(required=False)

FutureForex/documents/views.py
from django.views.generic.list import ListView
from django.http import (
    HttpResponse,
    HttpResponseBadRequest,
    HttpResponseRedirect,
    JsonResponse,
    FileResponse,
    Http404,
)
from django.shortcuts import render
from .models import (
    Customer,
    File,
    Notification,
    Document,
    UploadStatus,
    NotificationType,
    NotificationStatus,
)
from .forms import (
    FileUploadForm,
    DocumentRequestForm,
    DocumentFilterForm,
    NotificationFilterForm,
    CustomerFilterForm,
)
from .data_access.customer_access import get_customer_by_email, get_customers_by_rm
from .data_access.document_access import (
    update_document_status_from_upload_id,
    get_documents_with_customers_documents,
    get_rm_by_document_upload_id,
    get_customer_email_from_upload_id,
    get_file_from_upload_id,
    add_file_to_document_from_upload_id,
    create_document,
)
from .data_access.notification_access import (
    create_notification,
    get_notifications_by_rm,
    update_notification_status,
    get_unread_notifications_by_rm_count,
    mark_all_notifications_read_by_rm,
)
from .data_access.email_template_access import get_email_template_by_file_type
from .utilities import (
    generate_upload_id,
    is_valid_upload_request,
    fill_email_template,
)
from .constants import RM_ID, FROM_EMAIL, EXPIRY_DAYS
import logging
from django.core.mail import EmailMessage

logger = logging.getLogger(__name__)


def upload_file(request, upload_id):
    if not is_valid_upload_request(upload_id=upload_id):
        return HttpResponse(f"Upload for request {upload_id} is no longer valid")
    # Submit Upload request
    if request.method == "POST":
        form = FileUploadForm(request.POST, request.FILES)
        if form.is_valid():
            new_file = File(name=request.FILES["url"].name, url=request.FILES["url"])
            new_file.save()
            # Attach file to Document
            add_file_to_document_from_upload_id(upload_id=upload_id, file=new_file)
            # Update the status of the Document Request
            update_document_status_from_upload_id(
                upload_id=upload_id, status=UploadStatus.COMPLETED
            )
            # Create notification for RM of the customer
            create_notification(
                relationship_manager_id=get_rm_by_document_upload_id(
                    upload_id=upload_id
                ),
                type=NotificationType.FILE_UPLOAD.value,
                text=f"A new file has been uploaded by Customer {get_customer_email_from_upload_id(upload_id=upload_id)}",
            )
            return HttpResponse("Successfully Uploaded File.")
    # Render Upload form
    else:
        form = FileUploadForm()
    return render(request, "upload_file.html", {"form": form})


def create_document_request(request):
    if not request.method == "POST":
        return HttpResponseBadRequest("Bad Request")

    form = DocumentRequestForm(request.POST)
    if form.is_valid():
        email = form.cleaned_data["email"]
        customer = get_customer_by_email(email=email)
        name = form.cleaned_data["name"]
        file_type = form.cleaned_data["file_type"]

        # Generate upload id and link
        upload_id = generate_upload_id()
        upload_link = request.build_absolute_uri(f"/documents/upload/{upload_id}")
        # Get email template and fill in placeholders
        email_template = get_email_template_by_file_type(file_type=file_type)
        subject = email_template.subject
        replacement_dict = {
            "upload_link": upload_link,
            "expire_days": EXPIRY_DAYS,
            "rm_name": customer.relationship_manager.name,
        }
        body = fill_email_template(email_template, replacement_dict)
        # Send email to customer
        email = EmailMessage(
            subject=subject, body=body, from_email=FROM_EMAIL, to=[email]
        )
        email.send()
        # Create the document object
        create_document(
            customer=customer,
            name=name,
            file_type=file_type,
            email_blurb=email.message().as_string(),
            upload_id=upload_id,
        )

        return HttpResponseRedirect(request.META["HTTP_REFERER"])
    else:
        return HttpResponseBadRequest("Bad Request")


def download_document(request, upload_id):
    file = get_file_from_upload_id(upload_id=upload_id)
    # Return 404 to the user if they try to download a file that does not exist
    if not file:
        raise Http404("File not found")
    file_path = file.url.path
    # Download file by setting as_attachment
    response = FileResponse(open(file_path, "rb"), as_attachment=True)
    return response


def mark_notification_read(request, notification_id):
    update_notification_status(
        notification_id=notification_id, status=NotificationStatus.READ
    )
    return HttpResponseRedirect(request.META["HTTP_REFERER"])


def mark_all_notifications_read(request):
    mark_all_notifications_read_by_rm(relationship_manager_id=RM_ID)
    return HttpResponseRedirect(request.META["HTTP_REFERER"])


def get_unread_notification_count(request):
    unread_count = get_unread_notifications_by_rm_count(relationship_manager_id=RM_ID)
    return JsonResponse({"unread_count": unread_count})


class CustomerListView(ListView):
    model = Customer
    context_object_name = "customer_list"
    template_name = "customer_list.html"

    def get_queryset(self):
        # Unbound the form if there is not GET request data
        # https://medium.com/apollo-data-solutions-blog/django-initial-values-for-a-bound-form-fde7b363f79e
        # https://stackoverflow.com/questions/43091200/initial-not-working-on-form-inputs
        if len(self.request.GET):
            filter_form = CustomerFilterForm(self.request.GET)
        else:
            filter_form = CustomerFilterForm()
        if filter_form.is_valid():
            name_filter = filter_form.cleaned_data["name"]
            email_filter = filter_form.cleaned_data["email"]
            customer_list = get_customers_by_rm(
                relationship_manager_id=RM_ID, name=name_filter, email=email_filter
            )
        else:
            customer_list = get_customers_by_rm(relationship_manager_id=RM_ID)
        # For document request creation
        document_form = DocumentRequestForm()
        return {
            "customer_list": customer_list,
            "filter_form": filter_form,
            "document_form": document_form,
        }

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        queryset = self.get_queryset()
        context["customer_list"] = queryset["customer_list"]
        context["filter_form"] = queryset["filter_form"]
        context["document_form"] = queryset["document_form"]
        context["UploadStatus"] = UploadStatus

        return context


class DocumentView(ListView):
    model = Document
    context_object_name = "document_list"
    template_name = "document_list.html"

    def get_queryset(self):
        # Unbound the form if there is not GET request data
        # https://medium.com/apollo-data-solutions-blog/django-initial-values-for-a-bound-form-fde7b363f79e
        # https://stackoverflow.com/questions/43091200/initial-not-working-on-form-inputs
        if len(self.request.GET):
            filter_form = DocumentFilterForm(self.request.GET)
        else:
            filter_form = DocumentFilterForm()

        if filter_form.is_valid():
            email_filter = filter_form.cleaned_data["email"]
            status_filter = filter_form.cleaned_data["status"]
            sort_filter = filter_form.cleaned_data["sort"]
            document_list = get_documents_with_customers_documents(
                relationship_manager_id=RM_ID,
                email=email_filter,
                status=status_filter,
                sort=sort_filter,
            )
        else:
            document_list = get_documents_with_customers_documents(
                relationship_manager_id=RM_ID
            )
        customers = get_customers_by_rm(relationship_manager_id=RM_ID)
        # For document request creation        
        document_form = DocumentRequestForm()
        return {
            "document_list": document_list,
            "customers": customers,
            "filter_form": filter_form,
            "document_form": document_form,
        }

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        queryset = self.get_queryset()
        context["filter_form"] = queryset["filter_form"]
        context["document_form"] = queryset["document_form"]
        context["document_list"] = queryset["document_list"]
        context["customers"] = queryset["customers"]
        context["UploadStatus"] = UploadStatus

        return context


class NotificationView(ListView):
    model = Notification
    context_object_name = "notification_list"
    template_name = "notification_list.html"
    queryset = get_notifications_by_rm(RM_ID)

    # Unbound the form if there is not GET request data
    # https://medium.com/apollo-data-solutions-blog/django-initial-values-for-a-bound-form-fde7b363f79e
    # https://stackoverflow.com/questions/43091200/initial-not-working-on-form-inputs
    def get_queryset(self):
        if len(self.request.GET):
            filter_form = NotificationFilterForm(self.request.GET)
        else:
            filter_form = NotificationFilterForm()

        if filter_form.is_valid():
            status_filter = filter_form.cleaned_data["status"]
            type_filter = filter_form.cleaned_data["type"]
            sort_filter = filter_form.cleaned_data["sort"]
            notification_list = get_notifications_by_rm(
                relationship_manager_id=RM_ID,
                status=status_filter,
                type=type_filter,
                sort=sort_filter,
            )
        else:

FutureForex/documents/templates/base.html
<!-- Base view which handles tab logic and navigation between various tabs -->

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Documents</title>
    <!-- Some CSS, could probably be moved to separate file but small enough to maintain here for now -->
    <style>
        .tabs-container {
            display: flex;
            border-bottom: 1px solid #ccc;
        }

        .nav-link {
            flex: 1;
            text-align: center;
            padding: 10px;
            cursor: pointer;
            border: 1px solid #ccc;
            text-decoration: none;
            color: #333;
        }

        .nav-link.active {
            background-color: #007bff;
            color: #fff;
            border: none;
        }

        .tab-content {
            display: none;
        }

        .tab-content.active {
            display: block;
        }
    </style>
</head>

<body>
    <div class="tabs-container">
        <a class="nav-link" href="{% url 'customer_list' %}">Customers</a>
        <a class="nav-link" href="{% url 'document_list' %}">Documents</a>
        <a class="nav-link" href="{% url 'notification_list' %}">Notifications <span
                id="new_notification_count"></span></a>
    </div>

    <!-- Define all the tabs here -->
    <div class="tab-content" id="customers">
        {% block customers_tab_content %}{% endblock %}

    </div>
    <div class="tab-content" id="documents">
        {% block documents_tab_content %}{% endblock %}
    </div>
    <div class="tab-content" id="notifications">
        {% block notifications_tab_content %}{% endblock %}
    </div>

    <!-- The Javascript Tab logc to render the relevant tab -->
    <script>
        function showTab(tabId) {
            // Some logic get unread notifications. Not sure if can be done better but this works for now.
            fetch("{% url 'get_unread_notification_count'  %}")
                .then(response => response.json())
                .then(data => {
                    const newNotificationCount = document.getElementById('new_notification_count');
                    newNotificationCount.textContent = data.unread_count + " New";

                })

            // Firslty we disbale all tabs
            const tabLinks = document.querySelectorAll('.tab-content');
            tabLinks.forEach(tabLink => {
                tabLink.classList.remove('active');
            });

            // Then we set the current tab to active based on URL.
            document.getElementById(tabId).classList.add('active');

            // We also set the top tab nav links to active. This is to highlight the current tab
            const navLinks = document.querySelectorAll('.nav-link');
            navLinks.forEach(navLink => {
                navLink.classList.remove('active');
                if (navLink.getAttribute('href') === window.location.pathname) {
                    navLink.classList.add('active');
                }
            });

            const navLink = document.querySelector(`[href="#${tabId}"]`);
            navLink.classList.add('active');

        }

        // Logic to render tab based on the url
        document.addEventListener('DOMContentLoaded', function () {
            const currentPath = window.location.pathname;
            if (currentPath.includes("{% url 'customer_list' %}")) {
                showTab('customers');
            } else if (currentPath.includes("{% url 'document_list' %}")) {
                showTab('documents');
            } else if (currentPath.includes("{% url 'notification_list' %}")) {
                showTab('notifications');
            }

        });
    </script>
</body>

</html>

FutureForex/documents/templates/customer_list.html
<!-- Customer veiw-->
{% extends 'base.html' %}

{% block customers_tab_content %}
<div>
    <!-- Get Customers with some Filter Logic -->
    <h1>Customers</h1>
    <form method="GET" action="{% url 'customer_list' %}">
        <h2>Search Customers</h2>        
        {{filter_form}}
        <button type="submit">Search</button>
    </form>
    <!-- Render customers in a list -->
    <ul class="list-group">
        {% for customer in customer_list %}
        <li class="list-group-item">
            <div>
                <div>
                    <p><strong>Name:</strong> {{ customer.name }}</p>
                    <p><strong>Email:</strong> {{ customer.email }}</p>
                </div>
                <!-- Add button to toggle display of the customers documents -->
                <div>
                    <button class="btn" onclick="toggleDocuments('documents-{{ customer.id }}')">Show
                        Documents</button>
                </div>
            </div>
            <!-- Create document request. Might not be needed since w e have this logic in documents tab -->
            <div id="documents-{{ customer.id }}" style="display: none;">
                <form method="POST" action="{% url 'create_document_request' %}">
                    <h2>Create Document Request</h2>
                    {% csrf_token %}
                    <!-- Hide the email field since it is implicitly pulled from the current customer-->
                    <input type="hidden" name="email" id="email" value="{{ customer.email }}">                    
                    <p>
                        <strong>{{ document_form.name.label_tag }}</strong>
                        {{ document_form.name }}
                    </p>        
                    <p>
                        <strong>{{ document_form.file_type.label_tag }}</strong>
                        {{ document_form.file_type }} 
                    </p>        
                    <button type="submit" class="btn">Create</button>
                </form>
                <!-- Show all customers docuements-->
                <h3>Documents:</h3>
                <ul class="list-group">
                    {% for document in customer.document_set.all %}
                    <li class="list-group-item">
                        <div>
                            <div>
                                <p><strong>Name:</strong> {{ document.name }}</p>
                                <p><strong>Type:</strong> {{ document.get_file_type_display }}</p>
                                <p><strong>Status:</strong> {{ document.get_status_display }}</p>
                                <!-- Construct URL to be able to upload file -->
                                <p><strong>Upload URL:</strong> <a
                                        href="{{request.scheme}}://{{request.META.HTTP_HOST}}/documents/upload/{{ document.upload_id }}">{{document.upload_id}}</a></p>
                                <p><strong>Created at</strong> {{ document.created_at }}</p>
                            </div>
                            <!-- If document has been uploaded, show download option.-->
                            <div>
                                {% if document.status == UploadStatus.COMPLETED %}
                                <a href="{% url 'download_document' document.upload_id %}"
                                    class="btn btn-sm btn-primary">Download</a>
                                {% endif %}
                            </div>
                        </div>
                    </li>
                    {% empty %}
                    <li class="list-group-item">No Documents for customer.</li>
                    {% endfor %}
                </ul>
            </div>
        </li>
        {% empty %}
        <li class="list-group-item">No Customers assigned.</li>
        {% endfor %}
    </ul>
</div>

<script>
    // Logic to show/hide documents
    function toggleDocuments(elementId) {
        const element = document.getElementById(elementId);
        if (element.style.display === 'none') {
            element.style.display = 'block';
        } else {
            element.style.display = 'none';
        }
    }
</script>
{% endblock %}

FutureForex/documents/templates/document_list.html
<!-- Documents View -->
{% extends 'base.html' %}

{% block documents_tab_content %}
<div>
    <h1>Document Requests</h1>

    <form method="POST" action="{% url 'create_document_request' %}">
        <h2>Create Document Request</h2>
        {% csrf_token %}
        <p>
            <strong>{{ document_form.email.label_tag }}</strong>
            <select name="email" id="email">
                {% for customer in customers %}
                <option value="{{ customer.email }}">{{ customer.email }}</option>
                {% endfor %}
            </select>
        </p>        
        <p>
            <strong>{{ document_form.name.label_tag }}</strong>
            {{ document_form.name }}
        </p>        
        <p>
            <strong>{{ document_form.file_type.label_tag }}</strong>
            {{ document_form.file_type }} 
        </p>        
        <button type="submit" class="btn">Create</button>
    </form>
    
    <!-- Get Document Requests with some Filter Logic -->
    <form method="GET">
        <h2>Search Document Requests</h2>
        {{filter_form}}
        <button type="submit">Search</button>
    </form>
    <!-- Render the documents -->
    <ul class="list-group">
        {% for document in document_list %}
        <li class="list-group-item">
            <div>
                <div>
                    <p><strong>Email:</strong> {{ document.customer.email }}</p>
                    <p><strong>Name:</strong> {{ document.name }}</p>
                    <p><strong>Type:</strong> {{ document.get_file_type_display }}</p>
                    <p><strong>Status:</strong> {{ document.get_status_display }}</p>
                    <!-- Construct URL to be able to upload file -->
                    <p><strong>Upload URL:</strong> <a
                            href="{{request.scheme}}://{{request.META.HTTP_HOST}}/documents/upload/{{ document.upload_id }}">{{document.upload_id}}</a></p>
                    <p><strong>Created at</strong> {{ document.created_at }}</p>
                    <!-- If document has been uploaded, show download option.-->
                    {% if document.status == UploadStatus.COMPLETED %}
                    <a href="{% url 'download_document' document.upload_id %}"
                        class="btn btn-sm btn-primary">Download</a>
                    {% endif %}
                </div>
            </div>
        </li>
        {% empty %}
        <li class="list-group-item text-center">No Document Requests.</li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

FutureForex/documents/templates/notification_list.html
<!-- Notifications View -->
{% extends 'base.html' %}

{% block notifications_tab_content %}

<div>
    <h1>Notifications</h1>
    <!-- Get Notifications with some Filter Logic -->
    <form method="GET" action="{% url 'notification_list' %}">
        <h2>Search Notifications</h2>
        {{filter_form}}
        <button type="submit">Search</button>
    </form>

    <!-- Mark all notifications as read -->
    <form method="POST" action="{% url 'mark_all_notifications_read' %}">
        {% csrf_token %}
        </br>        
        <button type="submit" class="btn btn-primary">Mark All as Read</button>
    </form>

    {% csrf_token %}
    <!-- Render the Notifications -->
    <ul class="list-group">
        {% for notification in notification_list %}
        <!-- Slight hacky way to get notifications to pop. Would need to play around for best color highlight -->
        <li class="list-group-item" {% if notification.status == NotificationStatus.UNREAD %} style="background-color: dimgray; color: white;"
            {% endif %}>
            <div>
                <div>
                    <p><strong>Type:</strong> {{ notification.get_type_display }}</p>
                    <p><strong>Text:</strong> {{ notification.text }}</p>
                    <p><strong>Read:</strong> {{ notification.get_status_display }}</p>
                    <p><strong>Created at</strong> {{ notification.created_at }}</p>
                </div>
                <!-- If the notification is unread add a button to mark it as read -->
                {% if notification.status == NotificationStatus.UNREAD %}
                <form method="POST" action="{% url 'mark_notification_read' notification.id %}">
                    {% csrf_token %}
                    <button type="submit" class="btn">Mark as Read</button>
                </form>
                {% endif %}
            </div>
        </li>
        {% empty %}
        <li class="list-group-item">No Notifications.</li>
        {% endfor %}
    </ul>
</div>

<style>
    /* Define styles for read notifications */
    .bg-blue {
        background-color: blue;
        color: white;
        /* Optional: Change text color for better contrast */
    }
</style>

{% endblock %}

FutureForex/documents/templates/upload_file.html
<!-- File Upload Form -->
<!DOCTYPE html>
<html>

<head>
    <title>Upload File</title>
</head>

<body>
    <h1>Upload a File</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <!-- Django tag to be able to render the defined form FileUploadForm in forms.py -->
        {{ form.as_p }}
        <button type="submit">Upload</button>
    </form>
</body>

</html>